### ISSUE TITLE
OpenStack Network issue

### ISSUE THREAD

**Issue by coolpalani** [wako057/openstack-salt#4]
Hello,

After complete deployment, I followed this document to configure networks 
https://docs.openstack.org/newton/install-guide-ubuntu/launch-instance-networks-provider.html

but router gateway isn't working.
Did you get any chance to test the networks after completion of OpenStack installations
This is crucial part in openstack setup.
Kindly help me to fix this issue.

**Comment by wako057** [comment]
I globally think its due to the way you use your virtual vm that host the openstack solutions
Openstack need the complete control on an interface to work properly, it hasnt appear during my test but I had to setup
ops1.vm.network "private_network", ip: "xxx.xxxx.xxx.xxx", virtualbox__intnet: "wakonetwork"

**Comment by coolpalani** [comment]
Did you resole that network problem after setup that variable

**Comment by wako057** [comment]
I acutally didnt met the problem 
i push right now, but you have to configure 2 new variable in globals_vars

**Comment by wako057** [comment]
I actually had to 
salt '*' state.apply openstack.restart-services

**Comment by coolpalani** [comment]
I will try to deploy tomorrow and let you know.
if you are interested try to share your codes to saltstack main repository.
You are being recognized by many peoples.

Try here:

https://github.com/saltstack
https://github.com/salt-formulas
